name: SSH Command Runner

on:
  schedule:
    - cron: '*/20 * * * *' # 每 20 分钟运行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  run-ssh-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Connect to server and run command
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'cd ~/domains/$USER.serv00.net/vless && ./check_vless.sh'
