name: Restore Vless Service

on:
  schedule:
    - cron: "30 */4 * * *"  # 每4个小时运行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 根据需要选择其他版本

      - name: Install dependencies
        run: |
          pip install paramiko

      - name: Run restore script
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: python restore_vless.py
